/* Generated by _legacy/build.js from ../network.js — do not edit */
function _slicedToArray(r, e) { return _arrayWithHoles(r) || _iterableToArrayLimit(r, e) || _unsupportedIterableToArray(r, e) || _nonIterableRest(); }
function _nonIterableRest() { throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
function _iterableToArrayLimit(r, l) { var t = null == r ? null : "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (null != t) { var e, n, i, u, a = [], f = !0, o = !1; try { if (i = (t = t.call(r)).next, 0 === l) { if (Object(t) !== t) return; f = !1; } else for (; !(f = (e = i.call(t)).done) && (a.push(e.value), a.length !== l); f = !0); } catch (r) { o = !0, n = r; } finally { try { if (!f && null != t.return && (u = t.return(), Object(u) !== u)) return; } finally { if (o) throw n; } } return a; } }
function _arrayWithHoles(r) { if (Array.isArray(r)) return r; }
/* Familie Planner: relations web (netwerk.php).
   Nodes: our family (around "Ons gezin"), groups (class, team, work, family…), households and people from
   the address book. Links: member/contact → group (with role), contact → household, contact → "vriend van" member.
   Small force-directed layout drawn in SVG: drag nodes, drag the background to pan, scroll to zoom,
   click to see someone's connections, double-click to open their page. */
(function () {
  'use strict';

  var svg = document.getElementById('net');
  if (!svg || !window.FP) return;
  var _window$FP = window.FP,
    api = _window$FP.api,
    esc = _window$FP.esc,
    toast = _window$FP.toast;
  var NS = 'http://www.w3.org/2000/svg';
  var XLINK = 'http://www.w3.org/1999/xlink';
  var RADIUS = {
    home: 30,
    member: 26,
    group: 22,
    household: 13,
    contact: 17
  };
  var LENGTH = {
    home: 85,
    group: 95,
    household: 45,
    friend: 140
  };
  var panel = document.getElementById('net-panel');
  var filterBox = document.getElementById('net-filters');
  var search = document.getElementById('net-search');
  var nodes = [];
  var links = [];
  var byId = {};
  var hidden = {
    friend: false,
    household: false
  }; // plus group types: hidden[type] = true
  var focusSet = null; // ids shown in focus mode (someone + their neighbourhood)
  var selected = null;
  var alpha = 1;
  var running = false;
  var view = {
    x: 0,
    y: 0,
    k: 1
  };
  var userMoved = false; // after the user zooms or pans we stop re-fitting automatically

  var toggleClass = function toggleClass(node, cls, on) {
    var list = (node.getAttribute('class') || '').split(' ').filter(function (c) {
      return c && c !== cls;
    });
    if (on) list.push(cls);
    node.setAttribute('class', list.join(' '));
  };
  var el = function el(name, attrs, parent) {
    var n = document.createElementNS(NS, name);
    Object.keys(attrs || {}).forEach(function (k) {
      return n.setAttribute(k, attrs[k]);
    });
    if (parent) parent.appendChild(n);
    return n;
  };

  // ---------- Build ----------
  var defs = el('defs', {}, svg);
  var clip = el('clipPath', {
    id: 'netclip',
    clipPathUnits: 'objectBoundingBox'
  }, defs);
  el('circle', {
    cx: '0.5',
    cy: '0.5',
    r: '0.5'
  }, clip);
  var viewport = el('g', {
    class: 'net-viewport'
  }, svg);
  var linkLayer = el('g', {
    class: 'net-links'
  }, viewport);
  var nodeLayer = el('g', {
    class: 'net-nodes'
  }, viewport);
  // People without any connection yet gather in their own corner, ready to be dragged onto someone
  var looseLabel = el('text', {
    class: 'net-loose-label',
    'text-anchor': 'middle'
  }, viewport);
  looseLabel.textContent = 'Nog niet verbonden';
  var loosePoint = {
    x: 0,
    y: 0
  };

  /** Load the web. Later reloads (after connecting people) keep everyone where they were. */
  function loadGraph(first) {
    return api('graph').then(function (data) {
      var old = byId;
      byId = {};
      nodes = data.nodes;
      links = data.links.filter(function (l) {
        return l.source !== l.target;
      });
      nodes.forEach(function (n) {
        byId[n.id] = n;
        n.links = [];
      });
      links = links.filter(function (l) {
        return byId[l.source] && byId[l.target];
      });
      links.forEach(function (l) {
        l.s = byId[l.source];
        l.t = byId[l.target];
        l.s.links.push(l);
        l.t.links.push(l);
      });
      if (first) {
        placeInitially();
        buildFilters(data.groupTypes);
      } else {
        nodes.forEach(function (n) {
          var o = old[n.id];
          n.r = RADIUS[n.kind] || 16;
          n.vx = 0;
          n.vy = 0;
          n.x = o ? o.x : (Math.random() - 0.5) * 300;
          n.y = o ? o.y : (Math.random() - 0.5) * 300;
        });
      }
      draw();
      if (selected) select(byId[selected.id] || null);
    });
  }
  loadGraph(true).then(function () {
    var focus = svg.dataset.focus;
    if (focus && byId[focus]) {
      select(byId[focus]);
      setFocus(byId[focus]);
    }
    // Just added (quick add): put them in the middle, selected, ready to be dragged onto a group
    var fresh = byId[svg.dataset.new];
    if (fresh) {
      fresh.x = 60;
      fresh.y = -60;
      fresh.fixed = true; // stays put (others make room) until it is dragged
      select(fresh);
    }
    start(1);
    setTimeout(function () {
      if (fresh) {
        view.k = 1;
        center(fresh);
      } else if (!userMoved) fit();
    }, 700);
  }).catch(function (e) {
    svg.insertAdjacentHTML('afterend', "<p class=\"flash error\">".concat(esc(e.message), "</p>"));
  });
  function placeInitially() {
    var groups = nodes.filter(function (n) {
      return n.kind === 'group';
    });
    var members = nodes.filter(function (n) {
      return n.kind === 'member';
    });
    nodes.forEach(function (n) {
      n.x = (Math.random() - 0.5) * 60;
      n.y = (Math.random() - 0.5) * 60;
      n.vx = 0;
      n.vy = 0;
      n.r = RADIUS[n.kind] || 16;
    });
    members.forEach(function (n, i) {
      var a = i / members.length * Math.PI * 2;
      n.x = Math.cos(a) * 90;
      n.y = Math.sin(a) * 90;
    });
    groups.forEach(function (n, i) {
      var a = i / Math.max(1, groups.length) * Math.PI * 2;
      n.x = Math.cos(a) * 280;
      n.y = Math.sin(a) * 280;
    });
    // People start next to the first thing they are linked to
    nodes.forEach(function (n) {
      if (n.kind === 'contact' || n.kind === 'household') {
        var other = n.links.map(function (l) {
          return l.s === n ? l.t : l.s;
        }).find(function (o) {
          return o.kind !== 'contact';
        });
        if (other) {
          n.x = other.x + (Math.random() - 0.5) * 120;
          n.y = other.y + (Math.random() - 0.5) * 120;
        } else if (n.kind === 'contact' && !n.links.length) {
          n.x = 520 + Math.random() * 80;
          n.y = (Math.random() - 0.5) * 300;
        } // loose corner
        else {
          var a = Math.random() * Math.PI * 2;
          n.x = Math.cos(a) * 420;
          n.y = Math.sin(a) * 420;
        }
      }
    });
  }

  // ---------- Visibility (filters and focus) ----------
  function linkVisible(l) {
    if (hidden[l.kind]) return false;
    if (l.kind === 'group' && (hidden[l.s.type] || hidden[l.t.type])) return false;
    return nodeShown(l.s) && nodeShown(l.t);
  }
  function nodeShown(n) {
    if (focusSet && !focusSet[n.id]) return false;
    if (n.kind === 'group') return !hidden[n.type];
    if (n.kind === 'household') return !hidden.household;
    return true;
  }
  function visible(n) {
    if (!nodeShown(n)) return false;
    if (n.kind === 'home' || n.kind === 'member') return true;
    if (n.kind === 'contact' && !n.links.length) return true; // not connected yet: shown in the "Nog niet verbonden" corner
    // People and places without any visible connection would just float around: leave them out
    return n.links.some(function (l) {
      return linkVisible(l);
    });
  }
  function buildFilters(types) {
    var present = {};
    nodes.forEach(function (n) {
      if (n.kind === 'group') present[n.type] = true;
    });
    var html = '';
    Object.keys(types).forEach(function (k) {
      if (!present[k]) return;
      html += "<label class=\"pick sm\" style=\"--c:".concat(types[k].color, "\"><input type=\"checkbox\" checked data-f=\"").concat(k, "\"><span>").concat(types[k].emoji, " ").concat(esc(types[k].label), "</span></label>");
    });
    html += '<label class="pick sm" style="--c:#A0522D"><input type="checkbox" checked data-f="household"><span>🏠 Huishoudens</span></label>';
    html += '<label class="pick sm" style="--c:#8E6CDF"><input type="checkbox" checked data-f="friend"><span>👫 Vriend van</span></label>';
    filterBox.innerHTML = html;
    filterBox.addEventListener('change', function (e) {
      var f = e.target.dataset.f;
      if (!f) return;
      hidden[f] = !e.target.checked;
      refreshVisibility();
      start(0.5);
    });
  }

  // ---------- Drawing ----------
  function draw() {
    while (linkLayer.firstChild) linkLayer.removeChild(linkLayer.firstChild);
    while (nodeLayer.firstChild) nodeLayer.removeChild(nodeLayer.firstChild);
    links.forEach(function (l) {
      var c = l.kind === 'group' ? l.s.kind === 'group' ? l.s.color : l.t.color : l.kind === 'household' ? '#A0522D' : l.kind === 'friend' ? '#8E6CDF' : '#6C5CE7';
      l.el = el('line', {
        class: 'net-link ' + l.kind,
        stroke: c
      }, linkLayer);
      if (l.role) {
        var t = el('title', {}, l.el);
        t.textContent = l.role;
      }
    });
    nodes.forEach(function (n) {
      var g = el('g', {
        class: 'net-node ' + n.kind + (n.child ? ' child' : '')
      }, nodeLayer);
      el('circle', {
        r: n.r,
        fill: n.kind === 'group' || n.kind === 'household' || n.kind === 'home' ? '#fff' : n.color,
        stroke: n.color,
        'stroke-width': n.kind === 'member' || n.kind === 'home' ? 4 : 3
      }, g);
      if (n.photo) {
        var img = el('image', {
          x: -n.r,
          y: -n.r,
          width: n.r * 2,
          height: n.r * 2,
          'clip-path': 'url(#netclip)',
          preserveAspectRatio: 'xMidYMid slice'
        }, g);
        img.setAttributeNS(XLINK, 'xlink:href', 'foto.php?f=' + encodeURIComponent(n.photo) + '&s=t');
      } else {
        var t = el('text', {
          class: 'net-emoji',
          'text-anchor': 'middle',
          dy: '0.35em',
          'font-size': Math.round(n.r * (n.emoji ? 1.05 : 0.9))
        }, g);
        t.textContent = n.emoji || (n.label || '?').charAt(0).toUpperCase();
        if (!n.emoji) t.setAttribute('fill', '#fff');
      }
      var label = el('text', {
        class: 'net-label',
        'text-anchor': 'middle',
        y: n.r + 13
      }, g);
      label.textContent = n.label;
      var title = el('title', {}, g);
      title.textContent = (n.full || n.label) + (n.sub ? ' · ' + n.sub : '');
      g.addEventListener('pointerdown', function (e) {
        return nodeDown(e, n);
      });
      g.addEventListener('dblclick', function () {
        if (n.url) location.href = n.url;
      });
      n.el = g;
    });
    refreshVisibility();
    applyView();
  }
  function refreshVisibility() {
    nodes.forEach(function (n) {
      n.visible = visible(n);
      n.loose = n.kind === 'contact' && !n.links.length;
      n.el.style.display = n.visible ? '' : 'none';
      toggleClass(n.el, 'loose', n.loose);
    });
    // A tidy grid (alphabetical, 3 wide) in the loose corner
    nodes.filter(function (n) {
      return n.visible && n.loose;
    }).sort(function (a, b) {
      return (a.label || '').localeCompare(b.label || '');
    }).forEach(function (n, i, all) {
      n.slot = {
        col: i % 3,
        row: Math.floor(i / 3),
        rows: Math.ceil(all.length / 3)
      };
    });
    links.forEach(function (l) {
      l.visible = linkVisible(l) && l.s.visible && l.t.visible;
      l.el.style.display = l.visible ? '' : 'none';
    });
    highlight();
  }
  function render() {
    links.forEach(function (l) {
      if (!l.visible) return;
      l.el.setAttribute('x1', l.s.x.toFixed(1));
      l.el.setAttribute('y1', l.s.y.toFixed(1));
      l.el.setAttribute('x2', l.t.x.toFixed(1));
      l.el.setAttribute('y2', l.t.y.toFixed(1));
    });
    nodes.forEach(function (n) {
      if (n.visible) n.el.setAttribute('transform', "translate(".concat(n.x.toFixed(1), ",").concat(n.y.toFixed(1), ")"));
    });
    var loose = nodes.filter(function (n) {
      return n.visible && n.loose;
    });
    looseLabel.style.display = loose.length ? '' : 'none';
    if (loose.length) {
      var top = Infinity;
      var x = 0;
      loose.forEach(function (n) {
        top = Math.min(top, n.y - n.r);
        x += n.x;
      });
      looseLabel.setAttribute('x', (x / loose.length).toFixed(1));
      looseLabel.setAttribute('y', (top - 14).toFixed(1));
    }
  }

  // ---------- Simulation ----------
  function start(a) {
    alpha = Math.max(alpha, a);
    if (running) return;
    running = true;
    requestAnimationFrame(loop);
  }
  function loop() {
    for (var i = 0; i < 2; i++) tick();
    render();
    if (alpha > 0.02) requestAnimationFrame(loop);else {
      running = false;
      if (!userMoved) fit();
    }
  }
  function tick() {
    var vis = nodes.filter(function (n) {
      return n.visible;
    });
    var k = alpha;
    // Repulsion + collision
    for (var i = 0; i < vis.length; i++) {
      var a = vis[i];
      for (var j = i + 1; j < vis.length; j++) {
        var b = vis[j];
        if (a.dragging || b.dragging) continue; // don't push away what you're dragging onto
        var dx = b.x - a.x;
        var dy = b.y - a.y;
        var d2 = dx * dx + dy * dy;
        if (d2 < 0.01) {
          dx = Math.random() - 0.5;
          dy = Math.random() - 0.5;
          d2 = 0.25;
        }
        if (d2 > 360000) continue;
        var d = Math.sqrt(d2);
        var f = 2600 / d2 * k;
        var min = a.r + b.r + 14;
        if (d < min) f += (min - d) / d * 0.5;
        var fx = dx * f;
        var fy = dy * f;
        a.vx -= fx;
        a.vy -= fy;
        b.vx += fx;
        b.vy += fy;
      }
    }
    // Springs
    links.forEach(function (l) {
      if (!l.visible) return;
      var dx = l.t.x - l.s.x;
      var dy = l.t.y - l.s.y;
      var d = Math.sqrt(dx * dx + dy * dy) || 1;
      var len = LENGTH[l.kind] || 100;
      var f = (d - len) / d * 0.06 * (l.kind === 'friend' ? 0.4 : 1) * (k + 0.3);
      l.s.vx += dx * f;
      l.s.vy += dy * f;
      l.t.vx -= dx * f;
      l.t.vy -= dy * f;
    });
    // The corner for loose people: right of everything that is connected
    var right = 0;
    vis.forEach(function (n) {
      if (!n.loose && n.x > right) right = n.x;
    });
    loosePoint.x = right + 220;
    vis.forEach(function (n) {
      if (n.loose && n.slot) {
        var tx = loosePoint.x + n.slot.col * 70;
        var ty = loosePoint.y + (n.slot.row - (n.slot.rows - 1) / 2) * 70;
        n.vx = (tx - n.x) * 0.3;
        n.vy = (ty - n.y) * 0.3;
      } else {
        n.vx -= n.x * 0.003 * k;
        n.vy -= n.y * 0.003 * k;
      }
      if (n.fixed) {
        n.vx = 0;
        n.vy = 0;
        return;
      }
      n.vx *= 0.55;
      n.vy *= 0.55;
      n.x += Math.max(-40, Math.min(40, n.vx));
      n.y += Math.max(-40, Math.min(40, n.vy));
    });
    var home = byId.home;
    if (home && !home.fixed) {
      home.x *= 0.9;
      home.y *= 0.9;
    }
    alpha *= 0.99;
  }

  // ---------- Pan, zoom, drag ----------
  function applyView() {
    viewport.setAttribute('transform', "translate(".concat(view.x, ",").concat(view.y, ") scale(").concat(view.k, ")"));
  }
  function toWorld(cx, cy) {
    var r = svg.getBoundingClientRect();
    return {
      x: (cx - r.left - view.x) / view.k,
      y: (cy - r.top - view.y) / view.k
    };
  }
  function fit() {
    var vis = nodes.filter(function (n) {
      return n.visible;
    });
    if (!vis.length) return;
    var x0 = Infinity;
    var y0 = Infinity;
    var x1 = -Infinity;
    var y1 = -Infinity;
    vis.forEach(function (n) {
      x0 = Math.min(x0, n.x - n.r);
      y0 = Math.min(y0, n.y - n.r);
      x1 = Math.max(x1, n.x + n.r);
      y1 = Math.max(y1, n.y + n.r + 18);
    });
    var r = svg.getBoundingClientRect();
    var k = Math.min(1.8, Math.max(0.25, Math.min((r.width - 40) / (x1 - x0 || 1), (r.height - 40) / (y1 - y0 || 1))));
    view.k = k;
    view.x = r.width / 2 - (x0 + x1) / 2 * k;
    view.y = r.height / 2 - (y0 + y1) / 2 * k;
    applyView();
  }
  document.getElementById('net-fit').addEventListener('click', function () {
    userMoved = false;
    setFocus(null);
    fit();
  });
  svg.addEventListener('wheel', function (e) {
    e.preventDefault();
    var r = svg.getBoundingClientRect();
    var px = e.clientX - r.left;
    var py = e.clientY - r.top;
    userMoved = true;
    // Zoom by how far the wheel / trackpad pinch moved (a pinch sends many small ctrl+wheel events)
    var dy = e.deltaY * (e.deltaMode === 1 ? 16 : 1);
    var k = Math.max(0.15, Math.min(4, view.k * Math.exp(-dy * (e.ctrlKey ? 0.004 : 0.0012))));
    view.x = px - (px - view.x) / view.k * k;
    view.y = py - (py - view.y) / view.k * k;
    view.k = k;
    applyView();
  }, {
    passive: false
  });

  // ---------- Connecting by dragging one node onto another ----------
  var PAIRS = {
    'member|group': 1,
    'contact|group': 1,
    'contact|household': 1,
    'contact|member': 1
  };
  var canConnect = function canConnect(a, b) {
    return !!(PAIRS[a.kind + '|' + b.kind] || PAIRS[b.kind + '|' + a.kind]);
  };
  var connected = function connected(a, b) {
    return a.links.some(function (l) {
      return l.s === b || l.t === b;
    });
  };
  function dropTarget(n) {
    var best = null;
    var bestD = Infinity;
    nodes.forEach(function (o) {
      if (o === n || !o.visible || !canConnect(n, o) || connected(n, o)) return;
      var d = Math.hypot(o.x - n.x, o.y - n.y);
      // Hit area: the target itself, but never smaller than ~28px on screen (small when zoomed out)
      if (d < Math.max(o.r + n.r * 0.7, 28 / view.k) && d < bestD) {
        best = o;
        bestD = d;
      }
    });
    return best;
  }
  function describe(a, b, undo) {
    var person = a.kind === 'group' || a.kind === 'household' || a.kind === 'member' && b.kind === 'contact' ? b : a;
    var other = person === a ? b : a;
    var name = person.full || person.label;
    if (other.kind === 'group') return undo ? "".concat(name, " uit ").concat(other.label, " gehaald") : "".concat(name, " toegevoegd aan ").concat(other.label);
    if (other.kind === 'household') return undo ? "".concat(name, " woont niet meer bij ").concat(other.label) : "".concat(name, " woont nu bij ").concat(other.label);
    return undo ? "".concat(name, " is geen vriend meer van ").concat(other.label) : "".concat(name, " is nu vriend van ").concat(other.label);
  }
  function connect(a, b) {
    api('graph.link', {
      a: a.id,
      b: b.id
    }).then(function () {
      toast('✓ ' + describe(a, b, false), 'Ongedaan maken', function () {
        api('graph.unlink', {
          a: a.id,
          b: b.id
        }).then(function () {
          return loadGraph(false);
        }).then(function () {
          return start(0.3);
        });
      });
      return loadGraph(false);
    }).then(function () {
      return start(0.5);
    }).catch(function (e) {
      return toast(e.message);
    });
  }
  function disconnect(a, b) {
    api('graph.unlink', {
      a: a.id,
      b: b.id
    }).then(function () {
      toast(describe(a, b, true), 'Ongedaan maken', function () {
        api('graph.link', {
          a: a.id,
          b: b.id
        }).then(function () {
          return loadGraph(false);
        }).then(function () {
          return start(0.3);
        });
      });
      return loadGraph(false);
    }).then(function () {
      return start(0.4);
    }).catch(function (e) {
      return toast(e.message);
    });
  }
  var drag = null;
  function nodeDown(e, n) {
    e.stopPropagation();
    drag = {
      node: n,
      x: e.clientX,
      y: e.clientY,
      moved: false,
      id: e.pointerId
    };
    svg.setPointerCapture(e.pointerId);
  }
  // Two-finger pinch on touch screens: zoom exactly as far as the fingers move
  var touches = new Map();
  var pinch = null;
  svg.addEventListener('pointerdown', function (e) {
    if (e.pointerType !== 'mouse') touches.set(e.pointerId, {
      x: e.clientX,
      y: e.clientY
    });
    if (touches.size === 2) {
      var _Array$from = Array.from(touches.values()),
        _Array$from2 = _slicedToArray(_Array$from, 2),
        a = _Array$from2[0],
        b = _Array$from2[1];
      pinch = {
        dist: Math.hypot(a.x - b.x, a.y - b.y) || 1,
        k: view.k
      };
      drag = null;
      userMoved = true;
      return;
    }
    if (drag) return;
    drag = {
      pan: true,
      x: e.clientX,
      y: e.clientY,
      vx: view.x,
      vy: view.y,
      moved: false,
      id: e.pointerId
    };
    svg.setPointerCapture(e.pointerId);
  });
  svg.addEventListener('pointermove', function (e) {
    if (touches.has(e.pointerId)) touches.set(e.pointerId, {
      x: e.clientX,
      y: e.clientY
    });
    if (pinch && touches.size === 2) {
      var _Array$from3 = Array.from(touches.values()),
        _Array$from4 = _slicedToArray(_Array$from3, 2),
        a = _Array$from4[0],
        b = _Array$from4[1];
      var r = svg.getBoundingClientRect();
      var px = (a.x + b.x) / 2 - r.left;
      var py = (a.y + b.y) / 2 - r.top;
      var k = Math.max(0.15, Math.min(4, pinch.k * (Math.hypot(a.x - b.x, a.y - b.y) / pinch.dist)));
      view.x = px - (px - view.x) / view.k * k;
      view.y = py - (py - view.y) / view.k * k;
      view.k = k;
      applyView();
      return;
    }
    if (!drag || e.pointerId !== drag.id) return;
    var dist = Math.hypot(e.clientX - drag.x, e.clientY - drag.y);
    if (dist > 4) drag.moved = true;
    if (!drag.moved) return;
    if (drag.pan) {
      userMoved = true;
      view.x = drag.vx + (e.clientX - drag.x);
      view.y = drag.vy + (e.clientY - drag.y);
      applyView();
    } else {
      var p = toWorld(e.clientX, e.clientY);
      drag.node.x = p.x;
      drag.node.y = p.y;
      drag.node.fixed = true;
      drag.node.dragging = true;
      var target = dropTarget(drag.node);
      if (target !== drag.target) {
        if (drag.target) toggleClass(drag.target.el, 'drop-target', false);
        drag.target = target;
        if (target) toggleClass(target.el, 'drop-target', true);
      }
      render();
    }
  });
  var up = function up(e) {
    touches.delete(e.pointerId);
    if (touches.size < 2) pinch = null;
    if (!drag || e.pointerId !== drag.id) return;
    var d = drag;
    drag = null;
    if (d.node) {
      d.node.fixed = false;
      d.node.dragging = false;
      if (d.target) {
        toggleClass(d.target.el, 'drop-target', false);
        // Step back from the target so they don't end up on top of each other
        var dx = d.node.x - d.target.x || 1;
        var dy = d.node.y - d.target.y || 1;
        var len = Math.hypot(dx, dy);
        d.node.x = d.target.x + dx / len * (d.target.r + d.node.r + 30);
        d.node.y = d.target.y + dy / len * (d.target.r + d.node.r + 30);
        connect(d.node, d.target);
        return;
      }
      if (d.moved) start(0.3); // let the web settle around the new spot
      if (!d.moved) select(d.node === selected ? null : d.node);
    } else if (!d.moved) {
      select(null);
    }
  };
  svg.addEventListener('pointerup', up);
  svg.addEventListener('pointercancel', up);

  // ---------- Selection, panel, focus ----------
  function neighbours(n) {
    var out = {};
    out[n.id] = true;
    n.links.forEach(function (l) {
      if (linkVisible(l)) {
        out[l.s.id] = true;
        out[l.t.id] = true;
      }
    });
    return out;
  }
  function highlight() {
    var near = selected ? neighbours(selected) : null;
    nodes.forEach(function (n) {
      toggleClass(n.el, 'dim', !!near && !near[n.id]);
      toggleClass(n.el, 'selected', n === selected);
    });
    links.forEach(function (l) {
      return toggleClass(l.el, 'dim', !!near && !(l.s === selected || l.t === selected));
    });
  }
  function select(n) {
    selected = n;
    highlight();
    if (!n) {
      panel.hidden = true;
      return;
    }
    var groups = [];
    var people = [];
    n.links.forEach(function (l) {
      if (!linkVisible(l)) return;
      var o = l.s === n ? l.t : l.s;
      var item = {
        o: o,
        role: l.role,
        kind: l.kind
      };
      (o.kind === 'group' || o.kind === 'household' || o.kind === 'home' ? groups : people).push(item);
    });
    var row = function row(it) {
      return "<li><a href=\"#\" data-node=\"".concat(esc(it.o.id), "\">").concat(it.o.emoji && !it.o.photo ? esc(it.o.emoji) + ' ' : '').concat(esc(it.o.full || it.o.label), "</a>") + "".concat(it.role ? ' <span class="muted">· ' + esc(it.role) + '</span>' : '').concat(it.kind === 'friend' ? ' <span class="muted">· vriend van</span>' : '') + "".concat(canConnect(n, it.o) ? " <button class=\"link muted small\" data-unlink=\"".concat(esc(it.o.id), "\" title=\"Verbinding weghalen\">\u2715</button>") : '', "</li>");
    };
    panel.innerHTML = "<div style=\"display:flex;justify-content:space-between;gap:8px;align-items:flex-start\">\n        <div><h3>".concat(n.emoji && n.kind !== 'member' ? esc(n.emoji) + ' ' : '').concat(esc(n.full || n.label), "</h3>").concat(n.sub ? "<p class=\"muted small\" style=\"margin:2px 0 0\">".concat(esc(n.sub), "</p>") : '', "</div>\n        <button class=\"x\" data-close aria-label=\"Sluiten\">\xD7</button></div>\n      ").concat(groups.length ? "<h4>Hoort bij</h4><ul>".concat(groups.map(row).join(''), "</ul>") : '', "\n      ").concat(people.length ? "<h4>".concat(n.kind === 'group' || n.kind === 'household' ? 'Mensen' : 'Verbonden met', " (").concat(people.length, ")</h4><ul>").concat(people.map(row).join(''), "</ul>") : '', "\n      ").concat(n.kind === 'contact' || n.kind === 'member' ? '<p class="muted small" style="margin:10px 0 0">Tip: sleep deze persoon op een groep, huishouden of gezinslid om ze te verbinden.</p>' : '', "\n      <div class=\"pop-actions\">\n        ").concat(n.url ? "<a class=\"btn small\" href=\"".concat(esc(n.url), "\">Openen</a>") : '', "\n        <button class=\"btn small secondary\" data-focus>").concat(focusSet ? 'Alles tonen' : '🔎 Alleen dit netwerk', "</button>\n      </div>");
    panel.hidden = false;
  }
  panel.addEventListener('click', function (e) {
    var a = e.target.closest('[data-node]');
    if (a) {
      e.preventDefault();
      var n = byId[a.dataset.node];
      if (n) {
        select(n);
        center(n);
      }
      return;
    }
    var un = e.target.closest('[data-unlink]');
    if (un) {
      var o = byId[un.dataset.unlink];
      if (o && selected) disconnect(selected, o);
      return;
    }
    if (e.target.closest('[data-close]')) select(null);
    if (e.target.closest('[data-focus]')) {
      setFocus(focusSet ? null : selected);
      select(selected);
    }
  });
  /** Show only someone plus everything within two steps (or everything again with null). */
  function setFocus(n) {
    if (!n) {
      focusSet = null;
      refreshVisibility();
      start(0.4);
      return;
    }
    var set = {};
    set[n.id] = true;
    var frontier = [n];
    var _loop = function _loop() {
      var next = [];
      frontier.forEach(function (f) {
        return f.links.forEach(function (l) {
          var o = l.s === f ? l.t : l.s;
          if (!set[o.id] && o.kind !== 'home') {
            set[o.id] = true;
            next.push(o);
          }
        });
      });
      frontier = next.filter(function (o) {
        return o.kind !== 'member' || o === n;
      }); // don't fan out through the whole family
    };
    for (var depth = 0; depth < 2; depth++) {
      _loop();
    }
    focusSet = set;
    refreshVisibility();
    start(0.6);
    userMoved = false;
    setTimeout(fit, 900);
  }
  function center(n) {
    var r = svg.getBoundingClientRect();
    view.x = r.width / 2 - n.x * view.k;
    view.y = r.height / 2 - n.y * view.k;
    applyView();
  }
  search.addEventListener('input', function () {
    var q = search.value.trim().toLowerCase();
    if (q.length < 2) return;
    var n = nodes.find(function (x) {
      return x.visible && (x.full || x.label || '').toLowerCase().indexOf(q) > -1;
    });
    if (n) {
      select(n);
      center(n);
    }
  });
})();