/* Generated by _legacy/build.js from ../photo.js — do not edit */
function _slicedToArray(r, e) { return _arrayWithHoles(r) || _iterableToArrayLimit(r, e) || _unsupportedIterableToArray(r, e) || _nonIterableRest(); }
function _nonIterableRest() { throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); }
function _iterableToArrayLimit(r, l) { var t = null == r ? null : "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (null != t) { var e, n, i, u, a = [], f = !0, o = !1; try { if (i = (t = t.call(r)).next, 0 === l) { if (Object(t) !== t) return; f = !1; } else for (; !(f = (e = i.call(t)).done) && (a.push(e.value), a.length !== l); f = !0); } catch (r) { o = !0, n = r; } finally { try { if (!f && null != t.return && (u = t.return(), Object(u) !== u)) return; } finally { if (o) throw n; } } return a; } }
function _arrayWithHoles(r) { if (Array.isArray(r)) return r; }
function _createForOfIteratorHelper(r, e) { var t = "undefined" != typeof Symbol && r[Symbol.iterator] || r["@@iterator"]; if (!t) { if (Array.isArray(r) || (t = _unsupportedIterableToArray(r)) || e && r && "number" == typeof r.length) { t && (r = t); var _n = 0, F = function F() {}; return { s: F, n: function n() { return _n >= r.length ? { done: !0 } : { done: !1, value: r[_n++] }; }, e: function e(r) { throw r; }, f: F }; } throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method."); } var o, a = !0, u = !1; return { s: function s() { t = t.call(r); }, n: function n() { var r = t.next(); return a = r.done, r; }, e: function e(r) { u = !0, o = r; }, f: function f() { try { a || null == t.return || t.return(); } finally { if (u) throw o; } } }; }
function _unsupportedIterableToArray(r, a) { if (r) { if ("string" == typeof r) return _arrayLikeToArray(r, a); var t = {}.toString.call(r).slice(8, -1); return "Object" === t && r.constructor && (t = r.constructor.name), "Map" === t || "Set" === t ? Array.from(r) : "Arguments" === t || /^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(t) ? _arrayLikeToArray(r, a) : void 0; } }
function _arrayLikeToArray(r, a) { (null == a || a > r.length) && (a = r.length); for (var e = 0, n = Array(a); e < a; e++) n[e] = r[e]; return n; }
/* Familie Planner: photo picker with crop, zoom and rotate, used by every image upload field.
   - Clicking any <input type="file" accept="image/*"> opens this dialog instead of the file chooser.
   - Choose a file, drag one in, or paste with Ctrl+V (also works anywhere on a page with a photo field).
   - The cropped result (JPEG) is put back into the original input, so forms submit as before.
   - Multiple inputs (photos[]) collect several cropped photos, shown as thumbnails under the field.
   Aspect default: square for single photo fields (faces), the photo's own shape for multiple ones;
   override with data-aspect="1|0.8|1.5|orig" on the input. */
(function () {
  'use strict';

  // The cropped photo goes back into the form through DataTransfer; browsers without it keep the normal file field
  try {
    new DataTransfer();
  } catch (e) {
    return;
  }
  var MAX_OUT = 1600; // px, longest side of the result (the server resizes again anyway)
  var ASPECTS = [['1', 'Vierkant'], ['0.8', 'Staand'], ['1.5', 'Liggend'], ['orig', 'Origineel']];
  var esc = function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return {
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;'
      }[c];
    });
  };
  var toast = function toast(t) {
    return window.FP ? window.FP.toast(t) : alert(t);
  };
  var isPhotoInput = function isPhotoInput(el) {
    return el && el.matches && el.matches('input[type=file]') && /image/.test(el.accept || '');
  };
  var open = null; // the dialog that is currently open

  // Chosen photos per multiple input (DataTransfer can only be replaced as a whole)
  var collected = new WeakMap();

  // Replace the browser's English "Choose file" control with a Dutch button (hidden inputs stay as they are)
  function enhance() {
    document.querySelectorAll('input[type=file]').forEach(function (input) {
      if (!isPhotoInput(input) || input.hidden || input.dataset.native || input.dataset.enhanced) return;
      input.dataset.enhanced = '1';
      input.required = false; // a hidden required field would block the form without a message
      input.style.display = 'none';
      var b = document.createElement('button');
      b.type = 'button';
      b.className = 'btn secondary photo-btn';
      b.textContent = input.multiple ? "📷 Foto's kiezen of plakken" : '📷 Foto kiezen of plakken';
      b.onclick = function () {
        return openPicker(input);
      };
      input.before(b);
    });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', enhance);else enhance();
  document.addEventListener('click', function (e) {
    var input = e.target.closest && e.target.closest('input[type=file]');
    if (!isPhotoInput(input) || input.dataset.native) return;
    e.preventDefault();
    openPicker(input);
  }, true);

  // Ctrl+V anywhere: open the picker for the first photo field on the page
  document.addEventListener('paste', function (e) {
    if (open) return; // the dialog handles its own paste
    var file = imageFromClipboard(e);
    if (!file) return;
    var t = e.target;
    if (t && (t.isContentEditable || /^(INPUT|TEXTAREA)$/.test(t.tagName)) && !isPhotoInput(t)) return;
    // Skip disabled fields and fields inside a closed dialog
    var inputs = Array.from(document.querySelectorAll('input[type=file]')).filter(function (i) {
      return isPhotoInput(i) && !i.disabled && !(i.closest('dialog') && !i.closest('dialog[open]'));
    });
    var inDialog = inputs.filter(function (i) {
      return i.closest('dialog[open]');
    });
    if (inDialog.length) inputs = inDialog; // an open dialog (e.g. "＋ Persoon") goes first
    if (!inputs.length) return;
    e.preventDefault();
    if (inputs.length === 1 || !window.FP) {
      openPicker(inputs[0], file);
      return;
    }
    // Several photo fields on this page: ask which one first
    window.FP.choose('Voor welke foto?', 'Er staan meerdere fotovelden op deze pagina.', inputs.map(function (inp, i) {
      return {
        value: String(i),
        label: photoLabel(inp),
        primary: i === 0
      };
    })).then(function (v) {
      if (v !== null) openPicker(inputs[Number(v)], file);
    });
  });

  /** A readable name for a photo field: data-photo-label, the form's heading, or a name nearby. */
  function photoLabel(input) {
    if (input.dataset.photoLabel) return input.dataset.photoLabel;
    var form = input.closest('form');
    var h = form && form.querySelector('h2');
    if (h && h.textContent.trim()) return (input.multiple ? '' : 'Foto: ') + h.textContent.trim();
    var face = input.closest('.face');
    var name = face && face.querySelector('b');
    if (name) return 'Foto van ' + name.textContent.trim();
    return input.multiple ? "Foto's" : 'Foto';
  }
  function imageFromClipboard(e) {
    var items = e.clipboardData && e.clipboardData.items || [];
    var _iterator = _createForOfIteratorHelper(items),
      _step;
    try {
      for (_iterator.s(); !(_step = _iterator.n()).done;) {
        var it = _step.value;
        if (it.kind === 'file' && /^image\//.test(it.type)) return it.getAsFile();
      }
    } catch (err) {
      _iterator.e(err);
    } finally {
      _iterator.f();
    }
    return null;
  }
  function openPicker(input, initialFile) {
    var multiple = input.multiple;
    var aspect = input.dataset.aspect || (multiple ? 'orig' : '1');
    var d = document.createElement('dialog');
    d.className = 'modal photo-modal';
    d.innerHTML = "\n      <div class=\"modal-head\"><h2>\uD83D\uDCF7 ".concat(esc(photoLabel(input)), "</h2><button type=\"button\" class=\"x\" data-close aria-label=\"Sluiten\">\xD7</button></div>\n      <div class=\"modal-body\">\n        <div class=\"photo-drop\">\n          <div class=\"pd-icon\">\uD83D\uDDBC\uFE0F</div>\n          <p><b>Sleep een foto hierheen</b>, plak met <kbd>Ctrl</kbd>+<kbd>V</kbd>,<br>of</p>\n          <button type=\"button\" class=\"btn\" data-choose>Foto kiezen</button>\n          <input type=\"file\" accept=\"image/*\" data-native=\"1\" hidden>\n        </div>\n        <div class=\"photo-edit\" hidden>\n          <div class=\"crop-frame\"><img alt=\"\" draggable=\"false\"><div class=\"crop-grid\"></div></div>\n          <div class=\"crop-tools\">\n            <span class=\"zoom-row\">\uD83D\uDD0D <input type=\"range\" min=\"1\" max=\"4\" step=\"0.01\" value=\"1\" aria-label=\"Zoomen\"></span>\n            <div class=\"picker\">").concat(ASPECTS.map(function (_ref) {
      var _ref2 = _slicedToArray(_ref, 2),
        k = _ref2[0],
        l = _ref2[1];
      return "<label class=\"pick sm\"><input type=\"radio\" name=\"aspect\" value=\"".concat(k, "\"").concat(k === aspect ? ' checked' : '', "><span>").concat(l, "</span></label>");
    }).join(''), "</div>\n            <div style=\"display:flex;gap:6px;flex-wrap:wrap\">\n              <button type=\"button\" class=\"btn small secondary\" data-rotate title=\"Draaien\">\u21BB Draaien</button>\n              <button type=\"button\" class=\"btn small secondary\" data-other>Andere foto</button>\n            </div>\n          </div>\n          <p class=\"hint\">Sleep de foto om hem te verschuiven, zoom met de schuifbalk of het muiswiel.</p>\n        </div>\n      </div>\n      <div class=\"modal-foot\">\n        <span class=\"spacer\"></span>\n        <button type=\"button\" class=\"btn secondary\" data-close>Annuleren</button>\n        <button type=\"button\" class=\"btn\" data-use disabled>").concat(multiple ? 'Toevoegen' : 'Gebruiken', "</button>\n      </div>");
    document.body.appendChild(d);
    open = d;
    var drop = d.querySelector('.photo-drop');
    var edit = d.querySelector('.photo-edit');
    var frame = d.querySelector('.crop-frame');
    var imgEl = frame.querySelector('img');
    var zoom = d.querySelector('input[type=range]');
    var fileInput = d.querySelector('input[data-native]');
    var useBtn = d.querySelector('[data-use]');
    var src = null; // canvas holding the (rotated) source image
    var st = {
      scale: 1,
      min: 1,
      x: 0,
      y: 0,
      fw: 0,
      fh: 0
    };
    var close = function close() {
      d.close();
      d.remove();
      open = null;
    };
    d.querySelectorAll('[data-close]').forEach(function (b) {
      b.onclick = close;
    });
    d.addEventListener('cancel', function (e) {
      e.preventDefault();
      close();
    });
    d.querySelector('[data-choose]').onclick = function () {
      return fileInput.click();
    };
    d.querySelector('[data-other]').onclick = function () {
      return fileInput.click();
    };
    fileInput.onchange = function () {
      if (fileInput.files[0]) load(fileInput.files[0]);
      fileInput.value = '';
    };
    d.addEventListener('paste', function (e) {
      var f = imageFromClipboard(e);
      if (f) {
        e.preventDefault();
        load(f);
      }
    });
    ['dragenter', 'dragover'].forEach(function (t) {
      return d.addEventListener(t, function (e) {
        e.preventDefault();
        drop.classList.add('over');
      });
    });
    d.addEventListener('dragleave', function (e) {
      if (e.target === drop) drop.classList.remove('over');
    });
    d.addEventListener('drop', function (e) {
      e.preventDefault();
      drop.classList.remove('over');
      var f = Array.from(e.dataTransfer.files || []).find(function (x) {
        return /^image\//.test(x.type);
      });
      if (f) load(f);else toast('Dat is geen foto.');
    });
    function load(file) {
      if (!/^image\//.test(file.type)) {
        toast('Dat is geen foto.');
        return;
      }
      var url = URL.createObjectURL(file);
      var im = new Image();
      im.onload = function () {
        src = document.createElement('canvas');
        // Don't keep giant camera images around in the browser: 3000px is plenty to crop from
        var k = Math.min(1, 3000 / Math.max(im.naturalWidth, im.naturalHeight));
        src.width = Math.round(im.naturalWidth * k);
        src.height = Math.round(im.naturalHeight * k);
        src.getContext('2d').drawImage(im, 0, 0, src.width, src.height);
        URL.revokeObjectURL(url);
        drop.hidden = true;
        edit.hidden = false;
        useBtn.disabled = false;
        show();
      };
      im.onerror = function () {
        URL.revokeObjectURL(url);
        toast('Deze foto kan niet worden geopend. Probeer een jpg of png.');
      };
      im.src = url;
    }

    // Size the frame for the chosen shape and fit the photo so it covers the frame
    function show() {
      var ratio = aspect === 'orig' ? src.width / src.height : Number(aspect);
      var maxW = Math.min(460, d.querySelector('.modal-body').clientWidth - 4);
      var maxH = Math.min(420, window.innerHeight * 0.5);
      var fw = maxW;
      var fh = fw / ratio;
      if (fh > maxH) {
        fh = maxH;
        fw = fh * ratio;
      }
      st.fw = Math.round(fw);
      st.fh = Math.round(fh);
      frame.style.width = st.fw + 'px';
      frame.style.height = st.fh + 'px';
      frame.classList.toggle('round', aspect === '1' && !multiple);
      imgEl.src = src.toDataURL('image/jpeg', 0.92);
      st.min = Math.max(st.fw / src.width, st.fh / src.height);
      st.scale = st.min;
      st.x = (st.fw - src.width * st.scale) / 2;
      st.y = (st.fh - src.height * st.scale) / 2;
      zoom.value = 1;
      apply();
    }
    function clamp() {
      var w = src.width * st.scale;
      var h = src.height * st.scale;
      st.x = Math.min(0, Math.max(st.fw - w, st.x));
      st.y = Math.min(0, Math.max(st.fh - h, st.y));
    }
    function apply() {
      clamp();
      imgEl.style.width = src.width * st.scale + 'px';
      imgEl.style.height = src.height * st.scale + 'px';
      imgEl.style.transform = "translate(".concat(st.x, "px, ").concat(st.y, "px)");
    }
    // Zoom keeping the point (cx, cy) in the frame where it is
    function zoomTo(factor, cx, cy) {
      var ns = st.min * Math.max(1, Math.min(4, factor));
      var k = ns / st.scale;
      st.x = cx - (cx - st.x) * k;
      st.y = cy - (cy - st.y) * k;
      st.scale = ns;
      zoom.value = ns / st.min;
      apply();
    }
    zoom.addEventListener('input', function () {
      return zoomTo(Number(zoom.value), st.fw / 2, st.fh / 2);
    });
    frame.addEventListener('wheel', function (e) {
      e.preventDefault();
      var r = frame.getBoundingClientRect();
      var dy = e.deltaY * (e.deltaMode === 1 ? 16 : 1);
      zoomTo(st.scale / st.min * Math.exp(-dy * (e.ctrlKey ? 0.004 : 0.0012)), e.clientX - r.left, e.clientY - r.top);
    }, {
      passive: false
    });

    // Drag to move; two fingers to pinch-zoom
    var pointers = new Map();
    var last = null;
    var pinch = null;
    frame.addEventListener('pointerdown', function (e) {
      frame.setPointerCapture(e.pointerId);
      pointers.set(e.pointerId, {
        x: e.clientX,
        y: e.clientY
      });
      last = {
        x: e.clientX,
        y: e.clientY
      };
      if (pointers.size === 2) {
        var _Array$from = Array.from(pointers.values()),
          _Array$from2 = _slicedToArray(_Array$from, 2),
          a = _Array$from2[0],
          b = _Array$from2[1];
        pinch = {
          dist: Math.hypot(a.x - b.x, a.y - b.y),
          zoom: st.scale / st.min
        };
      }
    });
    frame.addEventListener('pointermove', function (e) {
      if (!pointers.has(e.pointerId)) return;
      pointers.set(e.pointerId, {
        x: e.clientX,
        y: e.clientY
      });
      if (pointers.size === 2 && pinch) {
        var _Array$from3 = Array.from(pointers.values()),
          _Array$from4 = _slicedToArray(_Array$from3, 2),
          a = _Array$from4[0],
          b = _Array$from4[1];
        var r = frame.getBoundingClientRect();
        zoomTo(pinch.zoom * Math.hypot(a.x - b.x, a.y - b.y) / pinch.dist, (a.x + b.x) / 2 - r.left, (a.y + b.y) / 2 - r.top);
        return;
      }
      st.x += e.clientX - last.x;
      st.y += e.clientY - last.y;
      last = {
        x: e.clientX,
        y: e.clientY
      };
      apply();
    });
    var up = function up(e) {
      pointers.delete(e.pointerId);
      if (pointers.size < 2) pinch = null;
      var p = Array.from(pointers.values())[0];
      if (p) last = {
        x: p.x,
        y: p.y
      };
    };
    frame.addEventListener('pointerup', up);
    frame.addEventListener('pointercancel', up);
    d.querySelectorAll('[name=aspect]').forEach(function (r) {
      return r.addEventListener('change', function () {
        aspect = r.value;
        show();
      });
    });
    d.querySelector('[data-rotate]').onclick = function () {
      var c = document.createElement('canvas');
      c.width = src.height;
      c.height = src.width;
      var ctx = c.getContext('2d');
      ctx.translate(c.width, 0);
      ctx.rotate(Math.PI / 2);
      ctx.drawImage(src, 0, 0);
      src = c;
      show();
    };
    useBtn.onclick = function () {
      // Cut out what is visible in the frame
      var sx = -st.x / st.scale;
      var sy = -st.y / st.scale;
      var sw = st.fw / st.scale;
      var sh = st.fh / st.scale;
      var k = Math.min(1, MAX_OUT / Math.max(sw, sh));
      var out = document.createElement('canvas');
      out.width = Math.max(1, Math.round(sw * k));
      out.height = Math.max(1, Math.round(sh * k));
      var ctx = out.getContext('2d');
      ctx.fillStyle = '#fff';
      ctx.fillRect(0, 0, out.width, out.height);
      ctx.imageSmoothingQuality = 'high';
      ctx.drawImage(src, sx, sy, sw, sh, 0, 0, out.width, out.height);
      out.toBlob(function (blob) {
        var file = new File([blob], 'foto-' + Date.now() + '.jpg', {
          type: 'image/jpeg'
        });
        setFiles(input, file, multiple);
        close();
        if (!multiple && input.hasAttribute('data-autosave')) autosave(input.form);
      }, 'image/jpeg', 0.9);
    };
    d.showModal();
    if (initialFile) load(initialFile);
  }

  /** "Gebruiken" also saves: click the form's own save button (so required fields are still checked). */
  function autosave(form) {
    if (!form) return;
    var buttons = Array.from(form.querySelectorAll('button')).filter(function (b) {
      return (b.getAttribute('type') || 'submit') === 'submit';
    });
    var save = buttons[buttons.length - 1];
    if (save) save.click();else form.submit();
  }

  /** Put the cropped photo into the real input and show a preview next to it. */
  function setFiles(input, file, multiple) {
    var list = multiple ? (collected.get(input) || []).concat(file) : [file];
    collected.set(input, list);
    var dt = new DataTransfer();
    list.forEach(function (f) {
      return dt.items.add(f);
    });
    input.files = dt.files;
    renderPreview(input, list, multiple);
    if (!multiple) {
      var remove = input.form && input.form.querySelector('[name=remove_photo]');
      if (remove) remove.checked = false;
    }
    input.dispatchEvent(new Event('change', {
      bubbles: true
    })); // e.g. smoelenboek submits on change
  }
  function renderPreview(input, list, multiple) {
    var box = input.nextElementSibling && input.nextElementSibling.classList.contains('photo-previews') ? input.nextElementSibling : null;
    if (!box) {
      box = document.createElement('div');
      box.className = 'photo-previews';
      input.after(box);
    }
    box.innerHTML = '';
    list.forEach(function (f, i) {
      var fig = document.createElement('span');
      fig.className = 'pp';
      var url = URL.createObjectURL(f);
      fig.innerHTML = "<img src=\"".concat(url, "\" alt=\"\">") + (multiple ? '<button type="button" aria-label="Verwijderen">×</button>' : '');
      var b = fig.querySelector('button');
      if (b) b.onclick = function () {
        var rest = list.filter(function (_, j) {
          return j !== i;
        });
        collected.set(input, rest);
        var dt = new DataTransfer();
        rest.forEach(function (x) {
          return dt.items.add(x);
        });
        input.files = dt.files;
        renderPreview(input, rest, multiple);
      };
      box.appendChild(fig);
    });
    var label = document.createElement('span');
    label.className = 'small muted';
    label.textContent = list.length ? multiple ? list.length + ' foto' + (list.length === 1 ? '' : "'s") + ' klaar · klik op het veld voor nog een' : 'Nieuwe foto klaar om op te slaan' : '';
    box.appendChild(label);
    input.classList.toggle('has-photo', list.length > 0);
  }
})();