/* Builds familyplanner/legacy/ for old browsers (LG webOS 3.x TVs = Chrome 38, anything without ES modules).
   Run after changing style.css, app.js, calendar.js or photo.js:
     cd familyplanner/_legacy && npm install --ignore-scripts && node build.js
   Output (committed, served as-is):
     legacy/style.css      style.css with CSS variables and color-mix() resolved to fixed colours + extra.css
     legacy/polyfills.js   core-js + fetch + pointer events + dom.js
     legacy/<name>.js      each script transpiled to ES5 by Babel */
'use strict';
const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'legacy');
const SCRIPTS = ['app.js', 'calendar.js', 'photo.js', 'network.js'];
fs.mkdirSync(OUT, { recursive: true });

// ---------- CSS ----------
/** Remove every "@media (prefers-color-scheme:dark){...}" block (brace matched). */
function dropBlocks(css, start) {
  let i;
  while ((i = css.indexOf(start)) !== -1) {
    let j = css.indexOf('{', i);
    let depth = 0;
    for (; j < css.length; j++) {
      if (css[j] === '{') depth++;
      else if (css[j] === '}' && --depth === 0) break;
    }
    css = css.slice(0, i) + css.slice(j + 1);
  }
  return css;
}

function parseColor(c) {
  c = c.trim();
  if (c === 'transparent') return [255, 255, 255, 0];
  let m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(c);
  if (m) {
    let h = m[1];
    if (h.length === 3) h = h.split('').map((x) => x + x).join('');
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16), 1];
  }
  m = /^rgba?\(([^)]*)\)$/i.exec(c);
  if (m) {
    const p = m[1].split(',').map((x) => parseFloat(x));
    return [p[0], p[1], p[2], p.length > 3 ? p[3] : 1];
  }
  return null;
}

/** color-mix(in srgb, A p%, B) → rgba(), when both colours are known. */
function resolveMix(value) {
  return value.replace(/color-mix\(in srgb,\s*([^,()]+(?:\([^)]*\))?)\s+(\d+(?:\.\d+)?)%\s*,\s*([^()]+?(?:\([^)]*\))?)\s*\)/g, (all, a, p, b) => {
    const A = parseColor(a);
    const B = parseColor(b);
    if (!A || !B) return all;
    const w = parseFloat(p) / 100;
    const alpha = A[3] * w + B[3] * (1 - w);
    const ch = (k) => (alpha ? Math.round((A[k] * A[3] * w + B[k] * B[3] * (1 - w)) / alpha) : 0);
    return alpha >= 1 ? `rgb(${ch(0)},${ch(1)},${ch(2)})` : `rgba(${ch(0)},${ch(1)},${ch(2)},${alpha.toFixed(3)})`;
  });
}

function buildCss() {
  let css = fs.readFileSync(path.join(ROOT, 'style.css'), 'utf8');
  css = dropBlocks(css, '@media (prefers-color-scheme:dark)');
  // Light theme variables from :root; values that pages/JS set inline get sensible defaults
  const vars = { '--hour': '48px', '--gutter': '56px', '--c': '#6C5CE7', '--ec': '#6C5CE7', '--fg-col': '8px', '--fg-row': '0' };
  const root = /:root\{([^}]*)\}/.exec(css);
  root[1].split(';').forEach((decl) => {
    const m = /^\s*(--[\w-]+)\s*:\s*(.+)\s*$/.exec(decl);
    if (m) vars[m[1]] = m[2];
  });
  const resolveVars = (v) => {
    let prev;
    do {
      prev = v;
      v = v.replace(/var\((--[\w-]+)(?:\s*,\s*([^()]*))?\)/g, (all, name, fallback) => vars[name] || (fallback != null ? fallback : '#6C5CE7'));
    } while (v !== prev);
    return v;
  };
  // Resolve inside declarations only (keeps selectors and custom property definitions intact)
  css = css.replace(/([{;])([a-z-]+)\s*:([^;{}]*var\([^;{}]*)/gi, (all, sep, prop, value) => sep + prop + ':' + resolveMix(resolveVars(value)));
  css = css.replace(/([{;])([a-z-]+)\s*:([^;{}]*color-mix\([^;{}]*)/gi, (all, sep, prop, value) => sep + prop + ':' + resolveMix(value));
  const extra = fs.readFileSync(path.join(__dirname, 'extra.css'), 'utf8');
  fs.writeFileSync(path.join(OUT, 'style.css'), '/* Generated by _legacy/build.js — do not edit */\n' + css + '\n' + extra);
}

// ---------- JS ----------
function buildJs() {
  const nm = (p) => fs.readFileSync(require.resolve(p), 'utf8');
  const polyfills = [
    nm('core-js-bundle/minified.js'),
    nm('whatwg-fetch/dist/fetch.umd.js'),
    nm('pepjs/dist/pep.js'),
    fs.readFileSync(path.join(__dirname, 'dom.js'), 'utf8'),
  ].join('\n;\n');
  fs.writeFileSync(path.join(OUT, 'polyfills.js'), '/* Generated by _legacy/build.js — do not edit */\n' + polyfills);
  for (const file of SCRIPTS) {
    const src = fs.readFileSync(path.join(ROOT, file), 'utf8');
    const out = babel.transformSync(src, {
      filename: file,
      babelrc: false,
      configFile: false,
      sourceType: 'script',
      presets: [['@babel/preset-env', { targets: { chrome: '38' }, modules: false }]],
    });
    fs.writeFileSync(path.join(OUT, file), '/* Generated by _legacy/build.js from ../' + file + ' — do not edit */\n' + out.code);
  }
}

buildCss();
buildJs();
console.log('legacy/ built:', fs.readdirSync(OUT).map((f) => f + ' ' + Math.round(fs.statSync(path.join(OUT, f)).size / 1024) + 'kB').join(', '));
