-- Starter idea bank (real suggestions, not demo data: kept when demo data is removed).
INSERT INTO fp_ideas (title, description, category, cost, season) VALUES
('Efteling', 'Hele dag. Kaartjes online kopen is goedkoper; ga op een doordeweekse vakantiedag voor minder rijen.', 'OUTING', '€€€', 'hele jaar'),
('Artis', 'Dierentuin in Amsterdam, met Micropia ernaast.', 'OUTING', '€€', 'hele jaar'),
('NEMO Science Museum', 'Proefjes doen; ideaal voor regenachtige dagen. Het dak is in de zomer gratis toegankelijk.', 'OUTING', '€€', 'hele jaar'),
('Kinderboerderij + picknick', 'Gratis en altijd leuk voor Bodi. Brood voor de geitjes (vraag wat mag).', 'OUTING', 'gratis', 'lente/zomer'),
('Speurtocht in het bos', 'Maak thuis een lijstje: dennenappel, veer, eikel, paddenstoel (niet aanraken!), slak.', 'OUTING', 'gratis', 'herfst'),
('Kabouterpad / kabouterwandeling', 'Veel natuurgebieden hebben een kabouterpad met opdrachtjes.', 'OUTING', 'gratis', 'hele jaar'),
('Strand + vlieger', 'Vlieger mee, emmer en schepjes, warme chocomel in de thermos.', 'OUTING', 'gratis', 'hele jaar'),
('Zwemparadijs', 'Subtropisch zwembad met glijbanen.', 'OUTING', '€€', 'winter'),
('Pannenkoekenboerderij', 'Fietstochtje en pannenkoek eten met speeltuin.', 'OUTING', '€€', 'hele jaar'),
('Klimbos / touwbaan', 'Kaila (8) kan de kinderroute, Bodi (5) vaak de mini-route; check lengte-eisen.', 'OUTING', '€€', 'lente/zomer'),
('Schaatsen op de ijsbaan', 'IJsbaan in de winter; schaatsjes huren kan vaak ter plekke.', 'OUTING', '€', 'winter'),
('Bibliotheek + voorleesuurtje', 'Veel bibliotheken hebben op woensdag of zaterdag voorlezen.', 'OUTING', 'gratis', 'hele jaar'),
('Aanbieden als klassenouder', 'Vraag de juf of er nog een klassenouder nodig is, of bied aan om te helpen bij één activiteit.', 'ENGAGEMENT', NULL, 'begin schooljaar'),
('Rijden bij een schoolreisje of uitstapje', 'Houd de nieuwsbrief in de gaten: rijouders zijn altijd welkom.', 'ENGAGEMENT', NULL, 'hele jaar'),
('Helpen bij sinterklaas- of kerstviering', 'Versieren, knutselen of opruimen.', 'ENGAGEMENT', NULL, 'december'),
('Voorleesouder of leesouder', 'Een half uurtje per week meelezen met kinderen uit de klas.', 'ENGAGEMENT', NULL, 'hele jaar'),
('Luizenmoeder of -vader', 'Na elke vakantie worden hoofden gecontroleerd; vaak zijn er handen nodig.', 'ENGAGEMENT', NULL, 'na vakanties'),
('Meedoen aan de ouderraad of MR', 'Meedenken over de school, een paar avonden per jaar.', 'ENGAGEMENT', NULL, 'hele jaar'),
('Trainer of scheidsrechter helpen bij de club', 'Bij voetbal of hockey is een ouder langs de lijn vaak heel welkom.', 'ENGAGEMENT', NULL, 'hele jaar'),
('Juf of meester bedanken', 'Een kaartje met een tekening van Kaila of Bodi, zomaar of aan het eind van het jaar.', 'ENGAGEMENT', NULL, 'juni/juli'),
('Kaartje sturen naar opa en oma', 'Laat de kinderen een tekening maken en stuur hem echt op met de post.', 'ATTENTION', NULL, 'hele jaar'),
('Buren iets lekkers brengen', 'Zelfgebakken koekjes of een bosje bloemen, zomaar.', 'ATTENTION', NULL, 'hele jaar'),
('Iemand met een baby of verhuizing een maaltijd brengen', 'Lasagne of soep brengen scheelt nieuwe ouders veel.', 'ATTENTION', NULL, 'hele jaar'),
('Appje na een belangrijke dag', 'Weet je dat iemand een sollicitatie, operatie of examen had? Vraag hoe het ging.', 'ATTENTION', NULL, 'hele jaar'),
('Terug uitnodigen', 'Waren de kinderen ergens spelen? Nodig het vriendje binnen een paar weken terug uit (zie Vriendjes).', 'ATTENTION', NULL, 'hele jaar'),
('Foto''s delen', 'Stuur een leuke foto van een feestje of uitje naar de andere ouders.', 'ATTENTION', NULL, 'hele jaar'),
('Bedankje na een kinderfeestje', 'Een appje aan de ouders: dank voor het leuke feestje!', 'ATTENTION', NULL, 'hele jaar'),
('Avondje uit eten met z''n tweeën', 'Oppas regelen en een nieuw restaurant proberen.', 'DATE', '€€', 'hele jaar'),
('Film of theater', 'Kaartjes op tijd kopen; combineer met een hapje vooraf.', 'DATE', '€€', 'hele jaar'),
('Wandeling + terras', 'Overdag terwijl de kinderen op school of bij een vriendje zijn.', 'DATE', '€', 'lente/zomer'),
('Weekendje weg zonder kinderen', 'Logeren bij opa en oma regelen.', 'DATE', '€€€', 'hele jaar'),
('Samen koken met een nieuw recept', 'Als de kinderen op bed liggen: iets uitgebreids koken met een goed glas wijn.', 'DATE', '€', 'hele jaar'),
('Borrel met de buurt', 'Een paar buren uitnodigen voor een hapje en drankje in de tuin of op straat.', 'DINNER', '€', 'zomer'),
('BBQ met vrienden en hun kinderen', 'Iedereen neemt iets mee; kinderen spelen in de tuin.', 'DINNER', '€€', 'zomer'),
('Etentje met vrienden thuis', 'Gourmetten of stamppotavond, lekker makkelijk.', 'DINNER', '€€', 'winter'),
('Ouders van klasgenoten uitnodigen', 'Een koffie- of borrelmoment na school om elkaar beter te leren kennen.', 'DINNER', '€', 'begin schooljaar'),
('Knutselmiddag: kastanjepoppetjes', 'Kastanjes, satéprikkers en wiebeloogjes.', 'ACTIVITY', 'gratis', 'herfst'),
('Koekjes bakken', 'Uitsteekvormpjes en glazuur, de kinderen mogen versieren.', 'ACTIVITY', '€', 'hele jaar'),
('Hut bouwen in de woonkamer', 'Dekens, stoelen en een zaklamp. Daarna een film in de hut.', 'ACTIVITY', 'gratis', 'winter'),
('Bordspellenmiddag', 'Kaila en Bodi kiezen om de beurt een spel.', 'ACTIVITY', 'gratis', 'hele jaar'),
('Zelf slijm maken', 'Lijm, scheerschuim en contactlensvloeistof. Wel buiten of op een oud tafelkleed!', 'ACTIVITY', '€', 'hele jaar'),
('Boek of cadeaubon van de boekhandel', 'Altijd goed voor kinderfeestjes van 5 tot 9 jaar.', 'GIFT', '€', 'hele jaar'),
('Knutselpakket of LEGO-setje', 'Tot ongeveer € 15 is gebruikelijk voor een kinderfeestje in de klas.', 'GIFT', '€', 'hele jaar'),
('Zelfgemaakt fotoboek voor opa en oma', 'Met foto''s van het afgelopen jaar.', 'GIFT', '€€', 'december'),
('Center Parcs of vakantiepark', 'Midweek of weekend met zwembad; veel te doen voor 5 en 8 jaar.', 'HOLIDAY', '€€€', 'hele jaar'),
('Kamperen in Nederland of Frankrijk', 'Camping met kinderclub en zwembad.', 'HOLIDAY', '€€', 'zomer'),
('Waddeneiland', 'Fietsen, strand, zeehonden kijken. Bijvoorbeeld Texel of Terschelling.', 'HOLIDAY', '€€', 'lente/zomer');
